services:
  - type: web
    env: node
    name: fh-prod-backend1
    repo: https://github.com/szx231/ship-paralect-root
    buildFilter:
      paths:
        - apps/api**
    buildCommand: npm && npm build --filter=backend
    startCommand: cd apps/api; npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fh-prod-db1
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: fh-prod-redis1
          type: redis
          property: connectionString
